import type { Building } from "./types"

// Sample data for campus buildings
export const buildings: Building[] = [
  {
    id: "new-building",
    name: "New Building",
    department: "School of Technology",
    description: "A modern facility housing various technology departments and labs.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Lecture Halls", "Computer Labs", "Research Centers", "Study Areas"],
    coordinates: {
      lat: 6.518611,
      lng: 3.372723,
    },
  },
  {
    id: "etf-building", 
    name: "ETF Building",
    department: "School of Engineering",
    description: "The Electrical and Telecommunications Engineering facility with specialized labs and equipment.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Electronics Lab", "Telecommunications Lab", "Workshop", "Lecture Rooms"],
    coordinates: {
      lat: 6.518834,
      lng: 3.372500,
    },
  },
  {
    id: "science-complex",
    name: "Science Complex",
    department: "School of Science",
    description: "A modern complex housing the departments of Mathematics, SLT, Foodtech, Statistic, and Computer Science.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Laboratories", "Lecture Halls", "Research Centers", "Staff Offices"],
    coordinates: {
      lat: 6.517899,
      lng: 3.372577,
    },
  },
  {
    id: "engineering-block",
    name: "Engineering Block",
    department: "School of Engineering",
    description:
      "Home to the various engineering departments including Civil, Mechanical, Electrical, and Computer Engineering.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Workshops", "Design Studios", "Computer Labs", "Lecture Rooms"],
    coordinates: {
      lat: 6.517094,
      lng: 3.374624,
    },
  },
  {
    id: "library",
    name: "Central Library",
    department: "Library Services",
    description:
      "The main library containing thousands of books, journals, and digital resources for students and staff.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Reading Rooms", "Digital Resource Center", "Archives", "Study Carrels"],
    coordinates: {
      lat: 6.517629,
      lng: 3.375300,
    },
  },
  {
    id: "art-design",
    name: "Art & Design Building",
    department: "School of Art, Design & Printing",
    description: "A creative hub for students studying Fine Arts, Graphic Design, and Printing Technology.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Art Studios", "Design Labs", "Exhibition Space", "Printing Workshop"],
    coordinates: {
      lat: 6.517800,
      lng: 3.373074,
    },
  },
  {
    id: "senate-building",
    name: "Senate Building",
    department: "Administration",
    description: "The administrative headquarters housing the Rector's office, other principal officers, and administrative staff.",
    image: "/placeholder.svg?height=400&width=600", 
    facilities: ["Council Chamber", "Conference Rooms", "Administrative Offices", "Reception Area"],
    coordinates: {
      lat: 6.518075,
      lng: 3.371708,
    },
  },
  {
    id: "college-hall",
    name: "College Hall", 
    department: "Student Affairs",
    description: "A large multipurpose hall used for academic gatherings, examinations, and other college-wide events.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Main Hall", "Stage", "Audio System", "Exam Hall", "Meeting Rooms"],
    coordinates: {
      lat: 6.516556,
      lng: 3.374922,
    },
  },
  {
    id: "old-smbs",
    name: "Old SMBS Building",
    department: "School of Management & Business Studies",
    description: "The original building of the School of Management and Business Studies, housing lecture rooms and offices.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Lecture Rooms", "Staff Offices", "Meeting Rooms", "Student Common Room"],
    coordinates: {
      lat: 6.519009,
      lng: 3.373189,
    },
  },
  {
    id: "multipurpose-hall",
    name: "Multipurpose Hall",
    department: "Student Affairs",
    description:
      "A large hall used for various events, ceremonies, and gatherings including matriculation, convocation, and cultural activities.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Stage", "Seating Area", "Sound System", "Lighting Equipment", "Backstage Rooms"],
    coordinates: {
      lat: 6.518717,
      lng: 3.376135,
    },
  },
  {
    id: "sports-complex",
    name: "Sports Complex",
    department: "Sports Unit",
    description:
      "A comprehensive sports facility with fields, courts, and indoor sports areas for various athletic activities.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Football Field", "Basketball Court", "Tennis Court", "Indoor Sports Hall", "Swimming Pool"],
    coordinates: {
      lat: 6.518735,
      lng: 3.374362,
    },
  },
  {
    id: "student-affairs",
    name: "Student Affairs",
    department: "Student Affairs",
    description: "A hub for student activities, organizations, and services designed to enhance campus life.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Student Union Office", "Cafeteria", "Recreation Rooms", "Meeting Spaces"],
    coordinates: {
      lat: 6.519449,
      lng: 3.374858, 
    },
  },
  {
    id: "bakassi",
    name: "Bakassi Hostel",
    department: "Student Affairs",
    description: "A student residential facility providing accommodation for students with modern amenities and facilities.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Rooms", "Common Areas", "Study Rooms", "Laundry Facilities"],
    coordinates: {
      lat: 6.519497,
      lng: 3.374047,
    },
  },
  {
    id: "environmental-studies",
    name: "Environmental Studies Building",
    department: "School of Environmental Studies",
    description: "Houses departments focused on environmental science, urban planning and related disciplines.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Lecture Rooms", "Design Studios", "Computer Labs", "Workshop Areas"],
    coordinates: {
      lat: 6.518186,
      lng: 3.375877,
    },
  },
  {
    id: "polymer-textile",
    name: "Polymer and Textile Building",
    department: "School of Engineering",
    description: "Specialized facility for polymer science and textile engineering studies with modern laboratories.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Textile Labs", "Polymer Labs", "Research Facilities", "Technical Workshops"],
    coordinates: {
      lat: 6.517341,
      lng: 3.375633,
    },
  },
  {
    id: "hospitality",
    name: "Hospitality Building",
    department: "School of Hospitality Management",
    description: "Training facility for hospitality and tourism management with practical learning spaces.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Training Kitchen", "Restaurant", "Hotel Simulation Room", "Lecture Rooms"],
    coordinates: {
      lat: 6.517239,
      lng: 3.375496,
    },
  },
  {
    id: "food-technology",
    name: "Food Technology Department",
    department: "Food Technology",
    description:
      "The Food Technology Department specializes in food processing, preservation, quality control and product development. Features modern laboratories and pilot plant facilities.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Food Processing Lab", "Quality Control Lab", "Product Development Kitchen", "Sensory Evaluation Room", "Food Packaging Unit"],
    coordinates: {
      lat: 6.517791,
      lng: 3.375973,
    },
  },
  {
    id: "bursary-registry",
    name: "Bursary and Registry",
    department: "Administration",
    description: "Houses the institution's financial and student records administrative offices.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Finance Office", "Student Records", "Administrative Offices", "Payment Points"],
    coordinates: {
      lat: 6.516958,
      lng: 3.374093,
    },
  },
  {
    id: "mechanical-workshop-1",
    name: "Mechanical Workshop 1",
    department: "School of Engineering",
    description: "Primary mechanical engineering workshop facility equipped for practical training.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Machine Shop", "Welding Area", "Tool Room", "Project Space"],
    coordinates: {
      lat: 6.517054,
      lng: 3.373760,
    },
  },
  {
    id: "mechanical-workshop-2", 
    name: "Mechanical Workshop 2",
    department: "School of Engineering",
    description: "Secondary mechanical engineering workshop for advanced practical sessions.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["CNC Lab", "Fabrication Area", "Testing Equipment", "Storage Facility"],
    coordinates: {
      lat: 6.517488,
      lng: 3.374353,
    },
  },
  {
    id: "zenith-bank",
    name: "Zenith Bank",
    department: "Banking Services",
    description: "On-campus banking facility providing financial services to students and staff.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["ATM Gallery", "Banking Hall", "Customer Service"],
    coordinates: {
      lat: 6.517582,
      lng: 3.374096,
    },
  },
  {
    id: "pg-hostel",
    name: "PG Hostel",
    department: "Student Housing",
    description: "Dedicated accommodation facility for postgraduate students.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Study Rooms", "Common Areas", "Kitchenette", "Laundry Facility"],
    coordinates: {
      lat: 6.519244,
      lng: 3.373658,
    },
  },
  {
    id: "hollyhood-hostel",
    name: "Hollyhood Hostel",
    department: "Student Housing",
    description: "Student accommodation facility with modern amenities.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Common Room", "Reading Room", "Laundry Area", "Security Post"],
    coordinates: {
      lat: 6.519550,
      lng: 3.375295,
    },
  },
  {
    id: "akata-hostel",
    name: "Akata Hostel",
    department: "Student Housing",
    description: "Student residential facility providing comfortable living spaces.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Study Areas", "Recreation Room", "Laundry Services", "Security"],
    coordinates: {
      lat: 6.519606,
      lng: 3.372915,
    },
  },
  {
    id: "complex-hostel",
    name: "Complex Hostel",
    department: "Student Housing",
    description: "Large residential complex for student accommodation with comprehensive facilities.",
    image: "/placeholder.svg?height=400&width=600",
    facilities: ["Study Halls", "Common Rooms", "Cafeteria", "Laundry"],
    coordinates: {
      lat: 6.519702,
      lng: 3.374613,
    },
  }
]
